CREATE TABLE transactions (
    id BIGSERIAL PRIMARY KEY,

    idempotency_key VARCHAR(255) UNIQUE NOT NULL,

    request_hash VARCHAR(64) NOT NULL,

    description TEXT NOT NULL,

    posted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);